version: '3.8'

services:
  qa-automation:
    image: ${DOCKER_REGISTRY_URL}/${CI_PROJECT_PATH}:staging-${CI_COMMIT_SHORT_SHA}
    container_name: qa-automation-staging
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=staging
      - LOG_LEVEL=INFO
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=qa_user
      - DB_PASSWORD=qa_password
      - DB_NAME=qa_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: pytest tests/e2e -k 'smoke or critical' --headless
    networks:
      - qa-network
    depends_on:
      - db
      - redis
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M

  db:
    image: postgres:14-alpine
    container_name: qa-db-staging
    environment:
      - POSTGRES_USER=qa_user
      - POSTGRES_PASSWORD=qa_password
      - POSTGRES_DB=qa_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - qa-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U qa_user -d qa_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  redis:
    image: redis:7-alpine
    container_name: qa-redis-staging
    networks:
      - qa-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.25'
          memory: 512M

  allure:
    image: frankescobar/allure-docker-service
    container_name: allure-service-staging
    ports:
      - "5050:5050"
    volumes:
      - ./reports/allure-results:/app/allure-results
      - ./reports/allure-report:/app/default-reports
    environment:
      - CHECK_RESULTS_EVERY_SECONDS=30
      - KEEP_HISTORY=true
    networks:
      - qa-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.25'
          memory: 512M

networks:
  qa-network:
    driver: overlay

volumes:
  postgres_data:
    driver: local