version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: qa_integration_postgres
    environment:
      POSTGRES_USER: qa_user
      POSTGRES_PASSWORD: qa_password
      POSTGRES_DB: qa_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U qa_user -d qa_db"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - pgdata_integration:/var/lib/postgresql/data

volumes:
  pgdata_integration:

