version: '3.8'

services:
  qa-automation:
    build:
      context: .
      dockerfile: Dockerfile
    image: qa-automation:dev
    container_name: qa-automation-dev
    volumes:
      - .:/app
      - ./reports:/app/reports
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=dev
      - LOG_LEVEL=DEBUG
    command: pytest tests/unit -v
    networks:
      - qa-network
    depends_on:
      - db
      - redis

  db:
    image: postgres:14-alpine
    container_name: qa-db-dev
    environment:
      - POSTGRES_USER=qa_user
      - POSTGRES_PASSWORD=qa_password
      - POSTGRES_DB=qa_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - qa-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U qa_user -d qa_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: qa-redis-dev
    ports:
      - "6379:6379"
    networks:
      - qa-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  selenium-hub:
    image: selenium/hub:4.10.0
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - qa-network

  chrome:
    image: selenium/node-chrome:4.10.0
    container_name: chrome-node
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - qa-network

  allure:
    image: frankescobar/allure-docker-service
    container_name: allure-service
    ports:
      - "5050:5050"
    volumes:
      - ./reports/allure-results:/app/allure-results
      - ./reports/allure-report:/app/default-reports
    environment:
      - CHECK_RESULTS_EVERY_SECONDS=10
      - KEEP_HISTORY=true
    networks:
      - qa-network

networks:
  qa-network:
    driver: bridge

volumes:
  postgres_data: